version: 2
jobs:
  build - test:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build-test
          environment:
            XXX: "${CIRCLE_SHA1::8}"
          command: |
            IMAGE_TAG=${CIRCLE_SHA1::8}
            echo ${IMAGE_TAG}
            echo ${XXX}
  tag-test:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test
  test1 > 1:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test
  test1 > 2:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test
  test2 > 1:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test
  test2 > 2:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test


workflows:
  version: 2
  test:
    jobs:
      - build - test:
      - tag-test:
          #requires:
          #  - build-test
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test1 > 1:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test1 > 2:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test2 > 1:
          requires:
            - test1 > 1
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - test2 > 2:
          requires:
            - test1 > 2
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/