version: 2
jobs:
  build-test:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build-test
          command: |
            echo build-test
  tag-test:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: tag-test
          command: |
            echo tag-test

workflows:
  version: 2
  test:
    jobs:
      - build-test
      - tag-test:
          requires:
            - build-test
          filters:
            tags:
              only: /.*/